[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test/unit"
remappings = ["@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/"]
#ffi = true # 允许foundry频繁运行命令 建议关闭
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
